#include "utils.h"
#include <random>

int generate_random(int min, int max)
{
    std::random_device rd;
    std::mt19937 generator(rd());
    std::uniform_int_distribution<int> distribution(min, max);

    return distribution(generator);

    // Use distrib to transform the random unsigned int
    // generated by gen into an int in [1, 100]

}


