/* Exercise 3:
 * Create a vector with 10 random elements in it. 
 * Rotate elements to the right by 3 positions with std::rotate.
*/

#include <iostream>
#include <vector>
#include <algorithm>
#include <random>

void generate_random_vector(std::vector<int>& v, const std::size_t& size)
{
    std::random_device rd;  
    std::mt19937 gen(rd()); 
    std::uniform_int_distribution<> distrib(1, 100);
 
    // Use distrib to transform the random unsigned int
    // generated by gen into an int in [1, 100]

    for (int n {0}; n != int(size); ++n)
    {
         v.push_back(int(distrib(gen)));
    }
}

void print(const std::vector<int>& v)
{
    for(auto element : v)
    {
        std::cout << element << ' ';
    }
    std::cout << '\n';
}

void rotate_values(std::vector<int>& vect, int n)
{
     std::rotate(vect.rbegin(), vect.rbegin() + n, vect.rend());
}

int main()
{
    std::vector<int> vect {};

    generate_random_vector(vect, 10);
    print(vect);
    rotate_values(vect, 3);
    print(vect);

    return 0;

}